### ISSUE TITLE
Tunnel started but connection timed out (WinError 10060)

### ISSUE THREAD

**Issue by MTDickens** [iOSRealRun/iOSRealRun-cli-17#7]
(.venv) PS D:\my softwares\FakeLocation\iOSRealRun-cli-17> python .\main.py
Your system version is 17.3.1
2024-03-04 22:04:34 mtdickens __main__[55556] INFO init done
2024-03-04 22:04:34 mtdickens __main__[55556] INFO starting tunnel
2024-03-04 22:06:15 mtdickens __main__[55556] INFO tunnel started
2024-03-04 22:06:15 mtdickens __main__[55556] INFO got route from HNroute.txt
2024-03-04 22:06:36 mtdickens __main__[55556] INFO tunnel process terminated
Bye
Traceback (most recent call last):
  File "D:\my softwares\FakeLocation\iOSRealRun-cli-17\main.py", line 93, in <module>
    main()
  File "D:\my softwares\FakeLocation\iOSRealRun-cli-17\main.py", line 63, in main
    with RemoteServiceDiscoveryService((address, port)) as rsd:
  File "D:\my softwares\FakeLocation\iOSRealRun-cli-17\.venv\Lib\site-packages\pymobiledevice3\remote\remote_service_discovery.py", line 120, in __enter__
    self.connect()
  File "D:\my softwares\FakeLocation\iOSRealRun-cli-17\.venv\Lib\site-packages\pymobiledevice3\remote\remote_service_discovery.py", line 50, in connect
    self.service.connect()
  File "D:\my softwares\FakeLocation\iOSRealRun-cli-17\.venv\Lib\site-packages\pymobiledevice3\remote\remotexpc.py", line 50, in connect
    self.sock = create_connection(self.address)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Scoop\apps\python\current\Lib\socket.py", line 852, in create_connection
    raise exceptions[0]
  File "C:\Scoop\apps\python\current\Lib\socket.py", line 837, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

**Comment by Geniucker** [comment]
这个就令人疑惑了

`git pull`
一下，然后设置环境变量
```
${env:DEBUG}="true"
```
然后运行，看看输出啥

**Comment by MTDickens** [comment]
这是运行结果：

```
(.venv) PS D:\my softwares\FakeLocation\iOSRealRun-cli-17> ${env:DEBUG}="true"
(.venv) PS D:\my softwares\FakeLocation\iOSRealRun-cli-17> python .\main.py
Your system version is 17.3.1
2024-03-05 12:35:27 mtdickens __main__[30476] INFO init done
2024-03-05 12:35:27 mtdickens __main__[30476] INFO starting tunnel
2024-03-05 12:35:28 mtdickens wintun[8072] INFO WetestUsbFilter driver use current version: 11.36.33.666, [11.36.33.666] tested.
2024-03-05 12:35:28 mtdickens wintun[8072] INFO WeTestUsbNcm driver use current version: 11.38.34.492, [11.36.59.886] tested.
2024-03-05 12:35:28 mtdickens wintun[8072] INFO use existing WeTestUsbFilter driver.
2024-03-05 12:35:28 mtdickens wintun[8072] INFO use existing WeTestUsbNcm driver.
2024-03-05 12:35:28 mtdickens zeroconf[8072] INFO Failed to set socket option on (('fe80::145b:f64a:82f9:6f5c', 0, 23), 23), this can happen if the network adapter is in a disconnected state
2024-03-05 12:35:31 mtdickens wintun[8072] INFO Failed to find matching adapter name: 找不到元素。 (Code 0x00000490)
2024-03-05 12:35:31 mtdickens wintun[8072] INFO Waiting for existing driver to unload from kernel
2024-03-05 12:37:04 mtdickens wintun[8072] INFO Failed to unload existing driver, which means a reboot will likely be required
2024-03-05 12:37:04 mtdickens wintun[8072] INFO Removing existing driver 0.14
2024-03-05 12:37:04 mtdickens wintun[8072] INFO Installing driver 15.14
2024-03-05 12:37:04 mtdickens wintun[8072] INFO Extracting driver
2024-03-05 12:37:04 mtdickens wintun[8072] INFO Installing driver
2024-03-05 12:37:05 mtdickens wintun[8072] INFO Creating adapter
2024-03-05 12:37:06 mtdickens __main__[30476] INFO tunnel started
2024-03-05 12:37:06 mtdickens __main__[30476] DEBUG tunnel address: fd91:acd4:bb4b::1, port: 51907
2024-03-05 12:37:06 mtdickens __main__[30476] INFO got route from HNroute.txt
2024-03-05 12:37:06 mtdickens wintun[8072] INFO Removed orphaned adapter "wintun 1"
2024-03-05 12:37:27 mtdickens __main__[30476] DEBUG Is process alive? False
2024-03-05 12:37:27 mtdickens __main__[30476] DEBUG terminating tunnel process
2024-03-05 12:37:27 mtdickens __main__[30476] INFO tunnel process terminated
Bye
Traceback (most recent call last):
  File "D:\my softwares\FakeLocation\iOSRealRun-cli-17\main.py", line 93, in <module>
    main()
  File "D:\my softwares\FakeLocation\iOSRealRun-cli-17\main.py", line 63, in main
    with RemoteServiceDiscoveryService((address, port)) as rsd:
  File "D:\my softwares\FakeLocation\iOSRealRun-cli-17\.venv\Lib\site-packages\pymobiledevice3\remote\remote_service_discovery.py", line 120, in __enter__
    self.connect()
  File "D:\my softwares\FakeLocation\iOSRealRun-cli-17\.venv\Lib\site-packages\pymobiledevice3\remote\remote_service_discovery.py", line 50, in connect
    self.service.connect()
  File "D:\my softwares\FakeLocation\iOSRealRun-cli-17\.venv\Lib\site-packages\pymobiledevice3\remote\remotexpc.py", line 50, in connect
    self.sock = create_connection(self.address)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Scoop\apps\python\current\Lib\socket.py", line 852, in create_connection
    raise exceptions[0]
  File "C:\Scoop\apps\python\current\Lib\socket.py", line 837, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
```

**Comment by TomPanda-cn** [comment]
我也有类似结果
`Your system version is 17.2.1
2024-03-05 13:25:21 LAPTOP-4DP9QG7M __main__[18688] INFO init done
2024-03-05 13:25:21 LAPTOP-4DP9QG7M __main__[18688] INFO starting tunnel
2024-03-05 13:25:26 LAPTOP-4DP9QG7M pymobiledevice3.remote.core_device_tunnel_service[29692] INFO Waiting user pairing consent
Process Process-1:
Traceback (most recent call last):
  File "G:\python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "G:\python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\init\tunnel.py", line 8, in tunnel_proc
    asyncio.run(connect.tunnel(server_rsd, queue))
  File "G:\python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "G:\python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\driver\connect.py", line 53, in tunnel
    async with start_tunnel(rsd, None) as tunnel_result:
  File "G:\python310\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 752, in start_tunnel
    with create_core_device_tunnel_service(service_provider, autopair=True) as service:
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 742, in create_core_device_tunnel_service
    service.connect(autopair=autopair)
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 330, in connect
    self._pair()
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 444, in _pair
    self._verify_proof()
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 496, in _verify_proof
    response = self._send_receive_pairing_data({
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 691, in _send_receive_pairing_data
    return self._receive_pairing_data()
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 697, in _receive_pairing_data
    response = self._receive_plain_response()['event']['_0']
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 720, in _receive_plain_response
    response = self.service.receive_response()
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\remotexpc.py", line 88, in receive_response
    frame = self._receive_next_data_frame()
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\remotexpc.py", line 150, in _receive_next_data_frame
    frame = self._receive_frame()
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\remotexpc.py", line 166, in _receive_frame
    buf = self._recvall(FRAME_HEADER_SIZE)
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\remotexpc.py", line 174, in _recvall
    chunk = self.sock.recv(size - len(data))
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
`

**Comment by MTDickens** [comment]
我重启了电脑，但是错误日志仍然和上面的一样。同时，我发现有两个未识别的网络。
![image](https://github.com/iOSRealRun/iOSRealRun-cli-17/assets/47918604/39b387b1-77f5-425b-bade-7ecd16f8c858)
![image](https://github.com/iOSRealRun/iOSRealRun-cli-17/assets/47918604/1d9a303e-75ae-44c1-b823-f577ed3899d1)
