### ISSUE TITLE
由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

### ISSUE THREAD

**Issue by TomPanda-cn** [iOSRealRun/iOSRealRun-cli-17#8]
在要求“信任”电脑及输入密码后报错
最后一条正常输出为
```python
2024-03-05 13:36:54 xxx pymobiledevice3.remote.core_device_tunnel_service[28000] INFO Waiting user pairing consent
```
以下为具体输出
```python
(venv) PS G:\BudaolepaoIOS17\iOSRealRun-cli-17> ${env:DEBUG}="true"
(venv) PS G:\BudaolepaoIOS17\iOSRealRun-cli-17> python main.py     
Your system version is 17.2.1
2024-03-05 13:36:48 xxx __main__[28488] INFO init done
2024-03-05 13:36:48 xxx __main__[28488] INFO starting tunnel
2024-03-05 13:36:51 xxx wintun[28000] INFO WetestUsbFilter driver use current version: 11.36.33.666, [11.36.33.666] tested.
2024-03-05 13:36:51 xxx wintun[28000] INFO WeTestUsbNcm driver use current version: 11.36.59.886, [11.36.59.886] tested.
2024-03-05 13:36:51 xxx wintun[28000] INFO use existing WeTestUsbFilter driver.
2024-03-05 13:36:51 xxx wintun[28000] INFO use existing WeTestUsbNcm driver.
2024-03-05 13:36:54 xxx pymobiledevice3.remote.core_device_tunnel_service[28000] INFO Waiting user pairing consent
Process Process-1:
Traceback (most recent call last):
  File "G:\python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "G:\python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\init\tunnel.py", line 8, in tunnel_proc
    asyncio.run(connect.tunnel(server_rsd, queue))
  File "G:\python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "G:\python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\driver\connect.py", line 53, in tunnel
    async with start_tunnel(rsd, None) as tunnel_result:
  File "G:\python310\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 752, in start_tunnel
    with create_core_device_tunnel_service(service_provider, autopair=True) as service:
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 742, in create_core_device_tunnel_service
    service.connect(autopair=autopair)
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 330, in connect
    self._pair()
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 444, in _pair
    self._verify_proof()
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 496, in _verify_proof
    response = self._send_receive_pairing_data({
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 691, in _send_receive_pairing_data
    return self._receive_pairing_data()
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 697, in _receive_pairing_data
    response = self._receive_plain_response()['event']['_0']
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 720, in _receive_plain_response
    response = self.service.receive_response()
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\remotexpc.py", line 88, in receive_response
    frame = self._receive_next_data_frame()
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\remotexpc.py", line 150, in _receive_next_data_frame
    frame = self._receive_frame()
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\remotexpc.py", line 166, in _receive_frame
    buf = self._recvall(FRAME_HEADER_SIZE)
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\remotexpc.py", line 174, in _recvall
    chunk = self.sock.recv(size - len(data))
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

**Comment by Geniucker** [comment]
怪，甚至service都没开起来，你试一下在先连接设备，然后虚拟环境以管理员身份`python -m pymobiledevice3 remote start-tunnel`

**Comment by TomPanda-cn** [comment]
还是在出现`2024-03-05 15:28:41 LAPTOP-4DP9QG7M pymobiledevice3.remote.core_device_tunnel_service[27636] INFO Waiting user pairing consent`后，手机提示是否信任电脑，输入密码之后就没反应了 再等一会就报错退出
以下是具体输出
```python
(venv) PS G:\BudaolepaoIOS17\iOSRealRun-cli-17> python -m pymobiledevice3 remote start-tunnel
2024-03-05 15:28:38 LAPTOP-4DP9QG7M wintun[27636] INFO WetestUsbFilter driver use current version: 11.36.33.666, [11.36.33.666] tested.
2024-03-05 15:28:38 xxx wintun[27636] INFO WeTestUsbNcm driver use current version: 11.36.59.886, [11.36.59.886] tested.
2024-03-05 15:28:38 xxx wintun[27636] INFO use existing WeTestUsbFilter driver.
2024-03-05 15:28:38 xxx wintun[27636] INFO use existing WeTestUsbNcm driver.
2024-03-05 15:28:41 xxx pymobiledevice3.remote.core_device_tunnel_service[27636] INFO Waiting user pairing consent
Traceback (most recent call last):
  File "G:\python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "G:\python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\__main__.py", line 156, in <module>
    main()
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\__main__.py", line 98, in main
    cli()
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\cli\cli_common.py", line 146, in wrapper
    func(*args, **kwargs)
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\cli\remote.py", line 197, in cli_start_tunnel
    asyncio.run(tunnel_task(rsd, secrets, script_mode, max_idle_timeout=max_idle_timeout, protocol=protocol),
  File "G:\python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "G:\python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\cli\remote.py", line 112, in tunnel_task
    async with start_tunnel(service_provider, secrets=secrets, max_idle_timeout=max_idle_timeout,
  File "G:\python310\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 752, in start_tunnel
    with create_core_device_tunnel_service(service_provider, autopair=True) as service:
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 742, in create_core_device_tunnel_service
    service.connect(autopair=autopair)
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 330, in connect
    self._pair()
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 444, in _pair
    self._verify_proof()
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 496, in _verify_proof
    response = self._send_receive_pairing_data({
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 691, in _send_receive_pairing_data
    return self._receive_pairing_data()
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 697, in _receive_pairing_data
    response = self._receive_plain_response()['event']['_0']
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 720, in _receive_plain_response
    response = self.service.receive_response()
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\remotexpc.py", line 88, in receive_response
    frame = self._receive_next_data_frame()
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\remotexpc.py", line 150, in _receive_next_data_frame
    frame = self._receive_frame()
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\remotexpc.py", line 166, in _receive_frame
    buf = self._recvall(FRAME_HEADER_SIZE)
  File "G:\BudaolepaoIOS17\iOSRealRun-cli-17\venv\lib\site-packages\pymobiledevice3\remote\remotexpc.py", line 174, in _recvall
    chunk = self.sock.recv(size - len(data))
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

**Comment by Geniucker** [comment]
那应该要找 [pymobiledevice3](https://github.com/doronz88/pymobiledevice3) 了，你可以给他提 issue并附上执行`python -m pymobiledevice3 remote start-tunnel`的结果

**Comment by MTDickens** [comment]
问题可能在于 [pymobiledevice3 #911](https://github.com/doronz88/pymobiledevice3/issues/911#issuecomment-2041025896)。库的作者认为 Windows 上的 driver 有很多问题，但是 wifi 连接就没有问题。

经我测试，也发现如果使用 usb driver 就会报错

```
INFO Failed to find matching adapter name
```

但是如果使用 wifi 就没有这个报错。

希望作者能实现一个用 wifi 连接的选项~~（~~我自己尝试魔改了一下，结果是 `WARNING:  Invalid HTTP request received.`，所以还是要麻烦作者来实现这个功能~~）~~

**Comment by geniucker-dev** [comment]
但是wifi是不是不能不能改定位
BTW号被封了现在动不了这个仓库🥲
